name: Generate Lighthouse Badges
on: [push]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lighthouse Badger
        uses: myactionway/lighthouse-badger-action@v2.3.2
        with:
          urls: 'https://astro-academics-page.vercel.app'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action_type: 'badges'
